In [3]:
import numpy as np

In [5]:
my_arr = np.arange(1000000)

In [7]:
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 16.7 ms, sys: 31.3 ms, total: 48.1 ms
Wall time: 47.6 ms


In [9]:
 %time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 465 ms, sys: 99.5 ms, total: 565 ms
Wall time: 565 ms


In [11]:
data = np.random.randn(2, 3)

In [12]:
data

array([[ 2.44748718, -0.41317975, -0.10911677],
       [ 0.30336097,  0.4632241 ,  1.12550123]])

In [13]:
data *10

array([[24.47487183, -4.1317975 , -1.09116773],
       [ 3.03360969,  4.63224096, 11.25501229]])

In [14]:
data + data

array([[ 4.89497437, -0.8263595 , -0.21823355],
       [ 0.60672194,  0.92644819,  2.25100246]])

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
data1 = [6, 7.5, 8, 0, 1]

In [18]:
arr1 = np.array(data1)

In [19]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [21]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int64')

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((10, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((3, 4, 7))

array([[[4.94065646e-324, 6.91240129e-310, 4.63837953e-310,
         6.91262902e-310, 4.94065646e-324, 4.94065646e-324,
         4.94065646e-324],
        [4.63837953e-310, 1.48219694e-323, 4.63837953e-310,
         4.63837953e-310, 4.63837953e-310, 4.63825840e-310,
         4.63837508e-310],
        [8.39911598e-323, 4.63837508e-310, 2.12199579e-313,
         8.39911598e-323, 4.63837508e-310, 6.91240129e-310,
         4.63837508e-310],
        [2.75859453e-313, 8.39911598e-323, 4.63837508e-310,
         8.39911598e-323, 4.63837508e-310, 3.39519327e-313,
         1.18575755e-322]],

       [[6.91259224e-310, 4.63825840e-310, 4.63837953e-310,
         2.12199579e-313, 0.00000000e+000, 0.00000000e+000,
         6.91240129e-310],
        [4.63837953e-310, 4.63837953e-310, 4.63837953e-310,
         4.94065646e-324, 1.08694442e-322, 4.63837953e-310,
         4.94065646e-324],
        [0.00000000e+000, 6.91240129e-310, 1.77863633e-321,
         4.94065646e-324, 6.91240129e-310, 4.63837953e-3

In [31]:
np.zeros((3, 4, 7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [33]:
np.full(3,9)

array([9, 9, 9])

In [35]:
np.eye(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
 arr1 = np.array([1, 2, 3], dtype=np.float64)

In [37]:
arr1

array([1., 2., 3.])

In [38]:
 arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr.dtype

dtype('float64')

In [44]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [45]:
arr.dtype

dtype('float64')

In [47]:
float_arr = arr.astype(np.float64)

In [48]:
float_arr.dtype

dtype('float64')

In [49]:
 arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [50]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [51]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])